// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates a demo showcasing Balder's capabilities.
 *
 * - generateBalderDemo - A function that generates a demo of Balder.
 * - GenerateBalderDemoInput - The input type for the generateBalderDemo function.
 * - GenerateBalderDemoOutput - The return type for the generateBalderDemo function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateBalderDemoInputSchema = z.object({
  customerNeed: z
    .string()
    .describe('The customer need or problem that Balder can solve.'),
});

export type GenerateBalderDemoInput = z.infer<typeof GenerateBalderDemoInputSchema>;

const GenerateBalderDemoOutputSchema = z.object({
  demoScript: z
    .string()
    .describe('A short demo script showcasing Balder in action.'),
});

export type GenerateBalderDemoOutput = z.infer<typeof GenerateBalderDemoOutputSchema>;

export async function generateBalderDemo(input: GenerateBalderDemoInput): Promise<GenerateBalderDemoOutput> {
  return generateBalderDemoFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateBalderDemoPrompt',
  input: {schema: GenerateBalderDemoInputSchema},
  output: {schema: GenerateBalderDemoOutputSchema},
  prompt: `You are an AI demo generator for Akalli's Balder agent.

    Balder is an AI customer support agent that automates customer service and support using AI and targeted learning. The agent closes sales, answers questions, and makes offers. It recognizes text, audio, and images and responds via audio when it receives an audio input.

    Generate a short demo script showing Balder in action, addressing the following customer need:
    {{{customerNeed}}}

    The demo script should include example customer interactions and successful automated sales scenarios.
    `,
});

const generateBalderDemoFlow = ai.defineFlow(
  {
    name: 'generateBalderDemoFlow',
    inputSchema: GenerateBalderDemoInputSchema,
    outputSchema: GenerateBalderDemoOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
